In [3]:
import pandas as pd

df = pd.read_csv("dataset/Bengaluru_House_Data.csv")

print(df.head())

              area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK

   society total_sqft  bath  balcony   price
0  Coomee        1056   2.0      1.0   39.07
1  Theanmp       2600   5.0      3.0  120.00
2      NaN       1440   2.0      3.0   62.00
3  Soiewre       1521   3.0      1.0   95.00
4      NaN       1200   2.0      1.0   51.00

In [4]:
print(df.shape)

(13320, 9)

In [5]:
print(df.columns)

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='str')

In [6]:
print(df.isnull().sum())

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [7]:
df = df.drop(['area_type','society','balcony','availability'], axis='columns')

print(df.head())

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [8]:
print(df.isnull().sum())

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [10]:
df = df.dropna()

print(df.isnull().sum())

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [11]:
df['bhk'] = df['size'].apply(lambda x: int(x.split(' ')[0]))

print(df.head())

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [12]:
df = df.drop('size', axis='columns')

print(df.head())

                   location total_sqft  bath   price  bhk
0  Electronic City Phase II       1056   2.0   39.07    2
1          Chikka Tirupathi       2600   5.0  120.00    4
2               Uttarahalli       1440   2.0   62.00    3
3        Lingadheeranahalli       1521   3.0   95.00    3
4                  Kothanur       1200   2.0   51.00    2

In [13]:
print(df['total_sqft'].unique()[:20])

<StringArray>
['1056', '2600', '1440', '1521', '1200', '1170', '2732', '3300', '1310',
 '1020', '1800', '2785', '1000', '1100', '2250', '1175', '1180', '1540',
 '2770',  '600']
Length: 20, dtype: str

In [14]:
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

In [15]:
df[~df['total_sqft'].apply(is_float)].head(10)

               location      total_sqft  bath    price  bhk
30            Yelahanka     2100 - 2850   4.0  186.000    4
122              Hebbal     3067 - 8156   4.0  477.000    4
137  8th Phase JP Nagar     1042 - 1105   2.0   54.005    2
165            Sarjapur     1145 - 1340   2.0   43.490    2
188            KR Puram     1015 - 1540   2.0   56.800    2
410             Kengeri  34.46Sq. Meter   1.0   18.500    1
549         Hennur Road     1195 - 1440   2.0   63.770    2
648             Arekere       4125Perch   9.0  265.000    9
661           Yelahanka     1120 - 1145   2.0   48.130    2
672        Bettahalsoor     3090 - 5002   4.0  445.000    4

In [16]:
df[~df['total_sqft'].apply(is_float)].head(10)

               location      total_sqft  bath    price  bhk
30            Yelahanka     2100 - 2850   4.0  186.000    4
122              Hebbal     3067 - 8156   4.0  477.000    4
137  8th Phase JP Nagar     1042 - 1105   2.0   54.005    2
165            Sarjapur     1145 - 1340   2.0   43.490    2
188            KR Puram     1015 - 1540   2.0   56.800    2
410             Kengeri  34.46Sq. Meter   1.0   18.500    1
549         Hennur Road     1195 - 1440   2.0   63.770    2
648             Arekere       4125Perch   9.0  265.000    9
661           Yelahanka     1120 - 1145   2.0   48.130    2
672        Bettahalsoor     3090 - 5002   4.0  445.000    4

In [17]:
def convert_sqft_to_num(x):
    tokens = x.split('-')
    
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2
    
    try:
        return float(x)
    
    except:
        return None

In [18]:
df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)

print(df.head())

                   location  total_sqft  bath   price  bhk
0  Electronic City Phase II      1056.0   2.0   39.07    2
1          Chikka Tirupathi      2600.0   5.0  120.00    4
2               Uttarahalli      1440.0   2.0   62.00    3
3        Lingadheeranahalli      1521.0   3.0   95.00    3
4                  Kothanur      1200.0   2.0   51.00    2

In [19]:
df = df.dropna()

In [20]:
print(df.head())

                   location  total_sqft  bath   price  bhk
0  Electronic City Phase II      1056.0   2.0   39.07    2
1          Chikka Tirupathi      2600.0   5.0  120.00    4
2               Uttarahalli      1440.0   2.0   62.00    3
3        Lingadheeranahalli      1521.0   3.0   95.00    3
4                  Kothanur      1200.0   2.0   51.00    2

In [21]:
df['price_per_sqft'] = (df['price'] * 100000) / df['total_sqft']

print(df.head())

                   location  total_sqft  bath   price  bhk  price_per_sqft
0  Electronic City Phase II      1056.0   2.0   39.07    2     3699.810606
1          Chikka Tirupathi      2600.0   5.0  120.00    4     4615.384615
2               Uttarahalli      1440.0   2.0   62.00    3     4305.555556
3        Lingadheeranahalli      1521.0   3.0   95.00    3     6245.890861
4                  Kothanur      1200.0   2.0   51.00    2     4250.000000

In [22]:
print(df['location'].value_counts())

location
Whitefield                                         532
Sarjapur  Road                                     392
Electronic City                                    302
Kanakpura Road                                     264
Thanisandra                                        232
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1298, dtype: int64

In [23]:
df['location'] = df['location'].apply(lambda x: x.strip())

In [24]:
location_stats = df['location'].value_counts()

print(location_stats)

location
Whitefield                                         533
Sarjapur  Road                                     392
Electronic City                                    304
Kanakpura Road                                     264
Thanisandra                                        235
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1287, dtype: int64

In [25]:
location_stats_less_than_10 = location_stats[location_stats <= 10]

df['location'] = df['location'].apply(
    lambda x: 'other' if x in location_stats_less_than_10 else x
)

In [26]:
df = df[df['total_sqft'] / df['bhk'] >= 300]

print(df.shape)

(12456, 6)

In [27]:
import numpy as np

In [28]:
def remove_pps_outliers(df):
    
    df_out = pd.DataFrame()
    
    for key, subdf in df.groupby('location'):
        
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        
        reduced_df = subdf[
            (subdf.price_per_sqft > (m - st)) &
            (subdf.price_per_sqft <= (m + st))
        ]
        
        df_out = pd.concat([df_out, reduced_df], ignore_index=True)
    
    return df_out

In [29]:
df = remove_pps_outliers(df)

print(df.shape)

(10242, 6)

In [30]:
def remove_bhk_outliers(df):
    
    exclude_indices = np.array([])
    
    for location, location_df in df.groupby('location'):
        
        bhk_stats = {}
        
        for bhk, bhk_df in location_df.groupby('bhk'):
            
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        
        for bhk, bhk_df in location_df.groupby('bhk'):
            
            stats = bhk_stats.get(bhk - 1)
            
            if stats and stats['count'] > 5:
                
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[bhk_df.price_per_sqft < stats['mean']].index.values
                )
    
    return df.drop(exclude_indices, axis='index')

In [31]:
df = remove_bhk_outliers(df)

print(df.shape)

(7317, 6)

In [32]:
df = df.drop('price_per_sqft', axis='columns')

In [33]:
print(df.head())

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [34]:
dummies = pd.get_dummies(df.location)

dummies.head()

,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,7th Phase JP Nagar,8th Phase JP Nagar,9th Phase JP Nagar,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [35]:
df = pd.concat([df, dummies.drop('other', axis='columns')], axis='columns')

print(df.head())

              location  total_sqft  bath  price  bhk  1st Block Jayanagar  \
0  1st Block Jayanagar      2850.0   4.0  428.0    4                 True
1  1st Block Jayanagar      1630.0   3.0  194.0    3                 True
2  1st Block Jayanagar      1875.0   2.0  235.0    3                 True
3  1st Block Jayanagar      1200.0   2.0  130.0    3                 True
4  1st Block Jayanagar      1235.0   2.0  148.0    2                 True

   1st Phase JP Nagar  2nd Phase Judicial Layout  2nd Stage Nagarbhavi  \
0               False                      False                 False
1               False                      False                 False
2               False                      False                 False
3               False                      False                 False
4               False                      False                 False

   5th Block Hbr Layout  ...  Vijayanagar  Vishveshwarya Layout  \
0                 False  ...        False                 False
1                 False  ...        False                 False
2                 False  ...        False                 False
3                 False  ...        False                 False
4                 False  ...        False                 False

   Vishwapriya Layout  Vittasandra  Whitefield  Yelachenahalli  Yelahanka  \
0               False        False       False           False      False
1               False        False       False           False      False
2               False        False       False           False      False
3               False        False       False           False      False
4               False        False       False           False      False

   Yelahanka New Town  Yelenahalli  Yeshwanthpur
0               False        False         False
1               False        False         False
2               False        False         False
3               False        False         False
4               False        False         False

[5 rows x 245 columns]

In [36]:
df = df.drop('location', axis='columns')

print(df.head())

   total_sqft  bath  price  bhk  1st Block Jayanagar  1st Phase JP Nagar  \
0      2850.0   4.0  428.0    4                 True               False
1      1630.0   3.0  194.0    3                 True               False
2      1875.0   2.0  235.0    3                 True               False
3      1200.0   2.0  130.0    3                 True               False
4      1235.0   2.0  148.0    2                 True               False

   2nd Phase Judicial Layout  2nd Stage Nagarbhavi  5th Block Hbr Layout  \
0                      False                 False                 False
1                      False                 False                 False
2                      False                 False                 False
3                      False                 False                 False
4                      False                 False                 False

   5th Phase JP Nagar  ...  Vijayanagar  Vishveshwarya Layout  \
0               False  ...        False                 False
1               False  ...        False                 False
2               False  ...        False                 False
3               False  ...        False                 False
4               False  ...        False                 False

   Vishwapriya Layout  Vittasandra  Whitefield  Yelachenahalli  Yelahanka  \
0               False        False       False           False      False
1               False        False       False           False      False
2               False        False       False           False      False
3               False        False       False           False      False
4               False        False       False           False      False

   Yelahanka New Town  Yelenahalli  Yeshwanthpur
0               False        False         False
1               False        False         False
2               False        False         False
3               False        False         False
4               False        False         False

[5 rows x 244 columns]

In [37]:
X = df.drop('price', axis='columns')

y = df.price

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=10
)

In [39]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [40]:
model.score(X_test, y_test)

0.8175889965469004

In [41]:
X.columns

Index(['total_sqft', 'bath', 'bhk', '1st Block Jayanagar',
       '1st Phase JP Nagar', '2nd Phase Judicial Layout',
       '2nd Stage Nagarbhavi', '5th Block Hbr Layout', '5th Phase JP Nagar',
       '6th Phase JP Nagar',
       ...
       'Vijayanagar', 'Vishveshwarya Layout', 'Vishwapriya Layout',
       'Vittasandra', 'Whitefield', 'Yelachenahalli', 'Yelahanka',
       'Yelahanka New Town', 'Yelenahalli', 'Yeshwanthpur'],
      dtype='str', length=243)

In [46]:
def predict_price(location, sqft, bath, bhk):
    
    x = pd.DataFrame(
        data=np.zeros((1, len(X.columns))),
        columns=X.columns
    )

    x['total_sqft'] = sqft
    x['bath'] = bath
    x['bhk'] = bhk

    if location in X.columns:
        x[location] = 1

    return model.predict(x)[0]

In [47]:
predict_price('1st Phase JP Nagar', 1000, 2, 2)

np.float64(83.16761667784696)

In [48]:
import pickle

pickle.dump(model, open('model/house_price_model.pickle', 'wb'))

In [51]:
import json

columns = {
    'data_columns': [col for col in X.columns]
}

with open("model/columns.json", "w") as f:
    f.write(json.dumps(columns))